---
title: "lasso_optimizer"
author: "Itzblend"
date: "27/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Setting up the control parameters for the train() function.
```{r}
set.seed(205)

myControl <- trainControl(method = "cv", number = 10)
lassoGrid <- expand.grid(alpha = 1, lambda = seq(0.001, 0.1, by = 0.0005))

lassoMod <- train(x = train1, y = all$SalePrice[!is.na(all$SalePrice)], method = "glmnet", trControl = myControl, tuneGrid = lassoGrid)

rmsePrint <- min(lassoMod$results$RMSE)

cat("The accuracy of the predictor is", rmsePrint)
```
Importances
```{r}
lassoVarImp <- varImp(lassoMod, scale = F)
lassoImportance <- lassoVarImp$importance

varselected <- length(which(lassoImportance$Overall != 0))
varnotselected <- length(which(lassoImportance$Overall == 0))

varselected
varnotselected
```
Following the usual steps in machine learning: setting the parameters for training, training itself and predicting the test set using the trained model (lassoMod)

Predictions
```{r}
lassoPred <- predict(lassoMod, test1)
predictions_test1 <- exp(lassoPred)
head(predictions_test1)
```